// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATUvpiCpul-fCG5gH2XUPRaCbWTdCbxdU',
    appId: '1:751792703942:web:c66587e4b11f6eef054ac7',
    messagingSenderId: '751792703942',
    projectId: 'snake-22a81',
    authDomain: 'snake-22a81.firebaseapp.com',
    storageBucket: 'snake-22a81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo8O0lMIgyKN9kyq00yRjLDHz47Iory5g',
    appId: '1:751792703942:android:59fec8e48eaf0b8e054ac7',
    messagingSenderId: '751792703942',
    projectId: 'snake-22a81',
    storageBucket: 'snake-22a81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6LRoI2qCrzsiQzlZgjYYc2GskgMbJau4',
    appId: '1:751792703942:ios:f66c77eb141abb4c054ac7',
    messagingSenderId: '751792703942',
    projectId: 'snake-22a81',
    storageBucket: 'snake-22a81.appspot.com',
    iosBundleId: 'com.vlad.snake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6LRoI2qCrzsiQzlZgjYYc2GskgMbJau4',
    appId: '1:751792703942:ios:7edfc8bdd1c3b6bc054ac7',
    messagingSenderId: '751792703942',
    projectId: 'snake-22a81',
    storageBucket: 'snake-22a81.appspot.com',
    iosBundleId: 'com.vlad.snake.RunnerTests',
  );
}
